### ISSUE TITLE
Figtext for many GTIs in sci_plots (minor issue)

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#14]
When the event file has a lot of GTIs, the display command
`plt.figtext(str(gtitable['START'][:]))`
of the astropy.Table automatically truncates the number of rows in the table, but there are still too many, and the list of GTIs overlaps with the title and goes out of the page.

That's a minor issue, but I can't find a way to truncate the display even more. There doesn't seem to be any way to tell 'print' or 'str()' to shorten the output of the astropy.Table 

Any ideas?

**Comment by paulray** [comment]
Maybe the code could count the number of lines in the str representation and then set the font size accordingly, so that the whole table fits?

**Comment by sguillot** [comment]
I did something like this:
- if there are more than 7 GTIs, the table shows only the first and last 3, replacing the middle ones by '...', and in the duration column, it shows the sum of the omitted GTIs.
- changed the font to courier to have fixed-width characters.

<img width="294" alt="Screenshot 2022-08-26 at 12 18 09" src="https://user-images.githubusercontent.com/22171129/186883027-8a8a5eaa-9d6c-4b3b-b708-749d490b8a23.png">
