### ISSUE TITLE
nicerfits2presto.py error when --dec DEC is a negative value

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#31]
When I run nicerfits2presto.py for a target with a negative declination, I get an error:
`>  nicerfits2presto.py --dt 0.125 --ra 17:32:03.3 --dec -34:45:18 merged_cut_barycorr.evt
usage: nicerfits2presto.py [-h] [--dt DT] [--ra RA] [--dec DEC]
                           [--observer OBSERVER]
                           evfile
nicerfits2presto.py: error: argument --dec: expected one argument`

This does *not* happen if the --dec is positive

**Comment by sguillot** [comment]
One solution could be to input RA and DEC as float in decimal degrees, and convert to hh:mm:ss.sss and dd:mm:ss.sss for the *inf file.

**Comment by paulray** [comment]
It is getting confused by the  minus sign. You can also just say --dec=-34:45:18

**Comment by scottransom** [comment]
Ah, that's a good old-fashioned astro-coding bug!  Lovely.  :-)
