### ISSUE TITLE
Make BKG_PLOT faster

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#34]
@paulray following your suggestion in #33 
Let me know how I can help.
Looking at bkg_plots.py, most plots already come from the MKF file, except the `overshootrate` and `undershootrate` plots., right?

**Comment by paulray** [comment]
Yep, I think the changes are quite small. It just needs to extract those rates from the mkf instead of the events. The main complexity might be different time binning in the .mkf than in the science data (which I think is `hkmet` in the code).

**Comment by sguillot** [comment]
I am not sure which columns of the mkf are needed for that:
`TOT_UNDER_COUNT` is for the undershoot rate, right ?
But `TOT_OVER_COUNT` does not seem to show the overshoot rate (when I compare the .mkf file with a prefilt_bkg.png plot)...

And I don't see where to get the Over+Under flags in the .mkf.
And the ratio of rejected events is `FPM_RATIO_REJ_COUNT`?

**Comment by paulray** [comment]
See the email I just forwarded to you.

**Comment by sguillot** [comment]
**To do:**
- [ ] Change the `cartographer.py` to use the over/under shoots from the .mkf file
- [ ] Clean up the geteventshoots functions to make par-pipe faster.
- [ ] anything else?

**Comment by sguillot** [comment]
There is probably still some clean up to do. For example, I think the calls to `quickhkshootrate` and `hkshootrate` in `NicerFileSet.py` are not really needed anymore.  Except that I am not sure about the use of `reset_rates`.  This is sometimes set to `None`, sometimes by summing the `MPU_UNDER_COUNT`, and sometimes calculated from the event file `self.etable` (this one seems to be the slowest).  I am a bit confused about what the `reset_rates` is use for.
