### ISSUE TITLE
nicerql seems to be in conflict with Matplotlib3.0

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#45]
I recommend not updating to Matplotlib3.0
The culprit seems to be:
`from matplotlib.cbook import is_scalar, dedent`
(sorry I lost the extra output...)

Reverting back to Matplotlib v2.2.3 solved the problem

**Comment by paulray** [comment]
Thanks for the tip!

**Comment by sguillot** [comment]
I think this is resolved since I have matplotlib v3.1.1, and nicerql is working fine.
Closing.
