### ISSUE TITLE
nitemplate.py is not python3 compatible

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#48]
This is due to the several python2 style `print` lines.

**Comment by paulray** [comment]
Ah!  I will futurize it. I'm starting to transition myself. I'm mostly just waiting for PRESTO's Python3 pull request to get merged then I can go whole hog (except for Fermi LAT, which seems to have no  Python3 plans as far as I can tell).

**Comment by sguillot** [comment]
I can take care of it. I just reported an issue to not forget about it

**Comment by paulray** [comment]
No worries, I'm just about to push.
It now works in Python3 but not Python2 :-)

**Comment by sguillot** [comment]
Is it a `pickle` vs `cPickle` issue?

**Comment by paulray** [comment]
No, futureize changed some "/" into old_div() calls and that broke the code in Python2. Not really sure why, but I fixed them.  I think pickle is working in both, but I didn't try loading either of the pickles back in.  It is pushed now if you want to try.
