### ISSUE TITLE
Hard-coded count rate for nopulsetest in ni_Htest_sortGTI

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#57]
Hi @kerrm,
I noticed that for the `nopulsetest` that uses only the S/N, the pred_rate was hard-coded, with a value that give very small exposure time for some data sets (e.g. for PSR J1012).
We should probably want to avoid that. Thoughts?

**Comment by kerrm** [comment]
Hi @sguillot ,
The routine isn't very sensitive to the value.  Basically you don't have to worry about the real value unless the true count rate is more than 20 or 30% of the background rate.  But it is true we still get these fluctuations when just a few GTI are included.  I think a better solution might be to disallow solutions with, say, less than 10 or 15% of the total exposure.  Do you think that would solve the edge cases you've seen?

**Comment by sguillot** [comment]
This has now been implemented (option `--minexp`)
