### ISSUE TITLE
Bug with option --usez in script ni_Htest_sortGTI.py

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#58]
Weird bug with a data set happened when adding the option `--usez`; and only with some values of `--emin` and `--emax`.
For example, `--emin=0.4 --emax=2.0` works fine, but `--emin=0.3 --emax=2.0` doesn't.

```
Traceback (most recent call last):
  File "/Users/sebastien/Softwares/NICERsoft/scripts/ni_Htest_sortgti.py", line 305, in <module>
    hsig = sig2sigma(chi2.sf(hs,4))
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/eventstats.py", line 76, in sig2sigma
    results[isig] = fsolve(inverfc, [8], (sig,))
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/scipy/optimize/minpack.py", line 147, in fsolve
    res = _root_hybr(func, x0, args, jac=fprime, **options)
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/scipy/optimize/minpack.py", line 225, in _root_hybr
    ml, mu, epsfcn, factor, diag)
ValueError: The array returned by a function changed size between calls
```

**Comment by paulray** [comment]
Maybe @kerrm can have a look

**Comment by kerrm** [comment]
@sguillot  could you send me the .evt file and full invocation you were using when you got this?  It does look weird... but maybe due to the auto-vectorization in sig2sigma.

**Comment by sguillot** [comment]
I'll check again if this issue persists.

**Comment by kerrm** [comment]
Oh yeah -- there is a bug I fixed in PINT in sig2sigma, and that needs to
propagated.  But I've been reluctant to do PRs with PINT trying to converge
on the paper etc.  Maybe a better fix at the moment is to just copy the
correct code over to NICERsoft?  We already have a special Htest version,
anyway...

**Comment by paulray** [comment]
Let's not leave bugs in PINT. Now is the time to fix them, before we tag v0.7.  Please do a PR.

**Comment by kerrm** [comment]
It turned out I had actually committed this fix (you merged it in
December), but I had some other updates so I went ahead and started a PR.
It improves the test coverage so I'm sure someone will want to merge it :)

**Comment by sguillot** [comment]
Works all fine :-)
