### ISSUE TITLE
Bug in new version of ni_Htest_sortGTI

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#63]
There is weird behaviour in `make_sn()` which causes the code to crash.

In some cases, the length of the arrays `gti_cts` and `gti_len` have different sizes, with `gti_cts` having a size larger than `gti_len` by 1 extra value.

I think I have managed to track back the difference to the array `gti_idx`, which is sometimes different between the old and new versions of ni_Htest_sortGTI.  So the TIMEZERO bug correction is causing `searchsorted(t1s,times)` to produce different arrays (I guess that's expected), but this  somehow produces a `gti_cts` (from `gti_cts = np.bincounts(gti_idx)`)with a different sizes between the two versions…

It’s happening with most ObsIDs that I have tried, but not all. I can’t figure out why…

**Comment by paulray** [comment]
@kerrm can you look at this?

**Comment by sguillot** [comment]
Seems to be working fine. I'll run a few more tests and close this one.

**Comment by sguillot** [comment]
All good!  Closing now.
#64
