### ISSUE TITLE
Speeding up ni_Htest_sortGTI

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#66]
@kerrm, let me know how it goes, and  how you are planning to do it.

I was thinking about implementing it in a multiprocessing.Pool, but if you have adjustments to the algorithms to do, I'll let you sort that you sort that out first.

**Comment by kerrm** [comment]
It gets really slow when there are tons of GTIs to handle -- the current big datasets have ~10,000.  But the background rate as a function of total exposure changes pretty slowly, at least in the central part of the data where the optimal solution is likely to lie.  So one easy way to speed it up is to only consider a fixed number of background rates and the GTI that correspond to them.  Even considering 1000 rates, which would be overkill oversampling, would speed it up by 10x for a large dataset.

The only thing stopping me is that it will require touching the code in a lot of places to change how things are calculated, so I need a few hours to concentrate on it.  I hope to get to it sometime this week.

**Comment by kerrm** [comment]
Rather than implementing this method, I saw a way to speed up the current version fairly substantially.  I haven't done a PR yet, but if you'd like to grab the version from my master, it has the changes in it.

Unfortunately, I'd already started to re-factor it in anticipation of making bigger changes, so there are also some differences in the way the data are handled.  Hoping I didn't introduce any more bugs!

**Comment by sguillot** [comment]
Great. I'll give it a try.

**Comment by sguillot** [comment]
@kerrm, after a quick try on the @TEST.list that I had sent you, your fast version (much faster indeed!) does not give the same output as the original version.

Even the total exposure (before GTI selection) is different: 415.43 ks with the fast version, and 414.81 with the "slow" original version.

I'll try to investigate...

**Comment by kerrm** [comment]
Yes, I noticed a small difference.  In fact, it was different from the
H-test optimization, related to the refactoring I did beforehand.  I didn't
see an obvious cause...
