### ISSUE TITLE
Replace basemap

### ISSUE THREAD

**Issue by paulray** [paulray/NICERsoft#69]
matplotlib.basemap has been deprecated. We should switch to cartopy or some other package for making the maps.

**Comment by paulray** [comment]
See here: https://pythonnumericalmethods.berkeley.edu/notebooks/chapter12.03-Working-with-Maps.html

**Comment by sguillot** [comment]
Pull request #79 

The cartopy maps are essentially identical to the basemap maps.
Actually, the continental coastlines (lakes, etc) are not shown, making the maps cleaner

![BASEMAP](https://user-images.githubusercontent.com/22171129/152029895-55f6b60c-2d1b-4365-9761-a7db71a61e98.png)
 
![CARTOPY](https://user-images.githubusercontent.com/22171129/152029887-4e8b9266-aaf3-4a68-bd46-9fb59ee9cc77.png)

**Comment by paulray** [comment]
Nice!
