### ISSUE TITLE
Improvements to cr_cut.py (C. Markwardt's suggestion)

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#81]
The steps 3 to 6 of the script `cr_cut.py` could be replaced by a single command `maketime`:

```
maketime merged_detid14.lc merged_detid14.gti "RATE < 1.0" name=NAME value=VALUE compact=NO prefr=0.5 postfr=0.5 premax=4.0 postmax=4.0 time=TIME
```

**Comment by sguillot** [comment]
I've been trying to implement the suggestion above; i.e., to make the gti file using `maketime`, rather than the more manual method with `ftcopy`, `ftcalc`, `ftlist` and `ftcreate`.  But I can't manage to obtain the same lightcurve after the cut.  Here are lightcurves with 16sec binning, with a cut at 3.0 c/s, first with the original version of `cr_cut.py`:
![Old_CRCUT](https://user-images.githubusercontent.com/22171129/184390949-4cbf5d8b-2c8c-4da0-8aa0-265e89f92c7a.png)

And now, two trials with `maketime` and different set of options:
1) for `prefr=0.5 postfr=0.5 premax=4.0 postmax=4.0` as suggested by Craig. These options cut out a *lot* of GTIs.
![New_CRCUT_try1](https://user-images.githubusercontent.com/22171129/184391307-cb8a2c6f-27d5-4b7a-8bae-1fa2c02aa504.png)

2) for `prefr=-1 postfr=-1 premax=-1 postmax=-1`. This one is better, but some GTIs are still above the CR cut of 3.0 c/s.
![New_CRCUT_try2](https://user-images.githubusercontent.com/22171129/184391832-75962966-f832-4f58-91d1-2c30a3319ef1.png)

The new version of the script replaces Steps 3 to 6 with:
```
cmd = [
    "maketime",
    lcfile,
    "gti.fits",
    '"RATE < {}"'.format(CRcut),
    "name=NAME value=VALUE compact=NO",
    "prefr=0.5 postfr=0.5 premax=4.0 postmax=4.0",     ### TRY 1
    #"prefr=-1 postfr=-1 premax=-1 postmax=-1",          ### TRY 2
    "time=TIME",
    "clobber=yes",
]
```

@paulray have you used `maketime` before ? Any idea about what could cause the differences ?
I've tried different combination of prefr, postfr, premax, postmax, but it's not clear to me what they actually do despite the 


If I try again but on a lightcurve with 1 sec binning, the resulting lightcurve a more similar (by about 100 events, out of 30k), but the `maketime` method still end up creating a lot of GTIs (which are concatenated in the old method)

**Comment by paulray** [comment]
If it is generating GTIs that are abutting but not merged (i.e. the end of one GTI is equal to the start of the next one), you can join those (and do other cool stuff) with `ftsdjustgti`.  Check out the fhelp on that. Craig wrote it.

**Comment by paulray** [comment]
Of course, if the current version of cr_cut works, then maybe we don't need to fuss with the maketime alternative?

**Comment by sguillot** [comment]
I can't seem to make it work with `ftadjustgti` and `maketime`, so as you suggested, we'll leave the current version ass is. Closing the issue.
