### ISSUE TITLE
psrpipe.py wants unzipped *orb and *att files

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#87]
By defaults, files from the HEASARC archives are gzipped. Running `nicerl2` creates unzipped `*evt` and `*mkf` files, but the `*orb` and `*att` files remained gzipped. This throws an `list index out of range error` at line 373 of psrpipe.py, which may be cryptic to new users.
```  
  File "/Users/sebastien/Softwares/NICERsoft/scripts/psrpipe.py", line 373, in <module>
    orbfile = glob(path.join(obsdir, "auxil/ni*.orb"))[0]
IndexError: list index out of range
```

I can think of a few solutions:

1. Catching the error with a warning that  `*orb` and `*att` files must be unzipped.
2. Replacing `glob(path.join(obsdir, "auxil/ni*.orb"))[0]` by `glob(path.join(obsdir, "auxil/ni*.orb*"))[0]`, which would work with the downloaded files by default (with only the gzipped) but which may become more complicated if both `.orb` and `.orb.gz` files are present. 
3. checking if `glob(path.join(obsdir, "auxil/ni*.orb"))` has length zero, and if it's the case using  with `glob(path.join(obsdir, "auxil/ni*.orb.gz"))`

There are probably other ways to solve this.
Any preferences or suggestions ?

**Comment by paulray** [comment]
I don't run into this, because my download script unzips the key files, but I think that trying your second solution makes sense.

**Comment by sguillot** [comment]
Done in c8c0a64610cc91d654ab4c5ba8b6de3ec704a17b

Perhaps we should do the same for the MKF files (with the same log.debug messages when multiple files are found)

**Comment by paulray** [comment]
Yes, handling the MKF files like that would be good. They can be very large, so gzipping can be useful.

**Comment by sguillot** [comment]
Done: 4c6f536c5e6968110e6bf6a8b3f1511a1dd9938b
closing the issue
