### ISSUE TITLE
Exception in sci_plots.py

### ISSUE THREAD

**Issue by paulray** [paulray/NICERsoft#93]
I'm getting exceptions sometimes in sci_plots when it tries to format the stringtable.
What I see is that at this line:
https://github.com/paulray/NICERsoft/blob/c9d684130c2dfe73881884eac8331438c313f7b8/nicer/sci_plots.py#L114
it grabs a table of the durations. Later it converts all the durations to float, but this fails because I'm getting '...' for one of the durations. I'm not sure why. Perhaps something is contracting down a longer table?

**Comment by paulray** [comment]
In my example, I added `print(stringtable_duration)` and got this:
```
['     DURATION    ', '        s        ', '-----------------', '            221.0', '            864.0', '            602.0', '            226.0', '            866.0', '            472.0', '            227.0', '            840.0', '            242.0', '            133.0', '            247.0', '            842.0', '            313.0', '             76.0', '             42.0', '            132.0', '            542.0', '             50.0', '             27.0', '            216.0', '            255.0', '              ...', '            163.0', '            799.0', '             91.0', '            196.0', '            779.0', '674.5389756560326', '            131.0', '            155.0', '            768.0', '            960.0', '            333.0', '            751.0', '            454.0', '             54.0', '             20.0', '            421.0', '            292.0', '            771.0', '            163.0', '            218.0', '            117.0', 'Length = 62 rows']
```

**Comment by sguillot** [comment]
The `print` statement is right after line 114 ?  
It is possible that `str(gtitable[...])` adds `...` when there are many GTIs in the fits file. But it is odd that only the `stringtable_duration` has `...` and not the other two string tables.
One solution would be to remove the line with the `...` in the three `stringtable_`.
I will try that.
